# Generated by Django 4.2.24 on 2025-10-23 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('fullname', models.CharField(blank=True, help_text='姓名', max_length=255, null=True, verbose_name='姓名')),
                ('role', models.CharField(choices=[('HEADQUARTER', '總公司'), ('AGENT', '代理商'), ('DISTRIBUTOR', '分銷商')], default='DISTRIBUTOR', help_text='用戶角色', max_length=20, verbose_name='用戶角色')),
                ('status', models.CharField(choices=[('ACTIVE', '上架'), ('INACTIVE', '下架'), ('ARCHIVED', '封存')], default='ACTIVE', help_text='用戶狀態', max_length=20, verbose_name='用戶狀態')),
                ('company', models.CharField(blank=True, help_text='公司名稱', max_length=200, null=True, verbose_name='公司名稱')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('email', models.EmailField(help_text='電子郵件', max_length=254, unique=True, verbose_name='電子郵件')),
                ('mobilephone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手機號碼')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_groups', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('parent', models.ForeignKey(blank=True, help_text='上層用戶', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='上層用戶')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['id'],
            },
        ),
    ]
