# Generated by Django 4.2.24 on 2025-12-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('HEADQUARTER', '總公司'), ('AGENT', '代理商'), ('DISTRIBUTOR', '分銷商'), ('PEER', '同業'), ('USER', '用戶')], default='DISTRIBUTOR', help_text='用戶角色', max_length=20, verbose_name='用戶角色'),
        ),
    ]
