# Generated by Django 4.2.24 on 2025-10-23 17:03

import business.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTopUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='剩餘金額')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': 'topup',
                'verbose_name_plural': 'topups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='支出金額')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='收入金額')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'income',
                'verbose_name_plural': 'income',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=business.utils.gen_order_tid, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='訂單編號')),
                ('warehouse', models.CharField(blank=True, max_length=255)),
                ('order_type', models.IntegerField(default=3)),
                ('reply_type', models.IntegerField(default=1)),
                ('order_code', models.CharField(max_length=255, null=True, verbose_name='Joytel Order Code')),
                ('tradeno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Trade No')),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='運費')),
                ('payment_type', models.CharField(choices=[('TOPUP', '儲值'), ('CASH', '現金'), ('DIRECT_BANK_TRANSFER', '銀行轉帳')], default='TOPUP', max_length=50, verbose_name='支付類型')),
                ('status', models.CharField(choices=[('PENDING', '待處理'), ('WAIT', '待付款'), ('PAID', '已付款'), ('WAIT_SHIP', '待發貨'), ('SHIPPING', '已發貨'), ('WAIT_PICKUP', '等待取貨'), ('DONE', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='訂單狀態')),
                ('remark', models.TextField(blank=True, verbose_name='訂單備註')),
                ('remark_admin', models.TextField(blank=True, verbose_name='管理員備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='訂單使用者')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='產品代碼')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='訂單產品價格')),
                ('quantity', models.IntegerField(verbose_name='訂單產品數量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='business.order', verbose_name='訂單')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variant', verbose_name='產品')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountTopUPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='金額')),
                ('balance_before', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='異動前金額')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='異動後金額')),
                ('log_type', models.CharField(choices=[('DEPOSIT', '儲值'), ('CONSUMPTION', '消費'), ('REFUND', '退款')], default='DEPOSIT', max_length=20, verbose_name='異動類型')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='已確認')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup_logs', to='business.order', verbose_name='相關訂單')),
                ('topup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='business.accounttopup', verbose_name='儲值')),
            ],
            options={
                'verbose_name': 'topup log',
                'verbose_name_plural': 'topup logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
