# Generated by Django 4.2.24 on 2025-10-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='item',
            field=models.CharField(choices=[('TAX', '稅務'), ('SALARY', '薪金'), ('RENT', '租金'), ('TRAVEL', '旅費'), ('ADVERTISEMENT', '廣告宣傳'), ('OFFICE_SUPPLIES', '辦公用品'), ('UTILITY_BILLS', '水電費'), ('BONUSES', '獎金'), ('SERVICE_FEE', '勞務費'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='支出項目'),
        ),
    ]
