# Generated by Django 4.2.24 on 2025-11-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='used_stocks',
            field=models.JSONField(blank=True, default=list, verbose_name='使用的庫存記錄'),
        ),
    ]
