# Generated by Django 4.2.24 on 2025-11-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_orderproduct_used_stocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('SHOPEE', '蝦皮'), ('WEBSITE', '官網'), ('LINE', 'LINE'), ('FACEBOOK', '臉書'), ('HANDOVER', '面交'), ('PEER', '同業'), ('GIFT', '禮物'), ('OTHER', '其他')], default='LINE', max_length=50, verbose_name='訂單來源'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('HOLDING', '保留中'), ('PENDING', '待處理'), ('WAIT', '待付款'), ('PAID', '已付款'), ('WAIT_SHIP', '待發貨'), ('SHIPPING', '已發貨'), ('WAIT_PICKUP', '等待取貨'), ('DONE', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='訂單狀態'),
        ),
    ]
