# Generated by Django 4.2.24 on 2025-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_order_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, choices=[('ERP', 'ERP系統'), ('SHOPEE', '蝦皮'), ('WEBSITE', '官網'), ('LINE', 'LINE'), ('FACEBOOK', '臉書'), ('HANDOVER', '面交'), ('PEER', '同業'), ('GIFT', '禮物'), ('OTHER', '其他')], default='LINE', max_length=50, null=True, verbose_name='訂單來源'),
        ),
    ]
