# Generated by Django 4.2.24 on 2025-11-18 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0010_alter_order_order_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=255, unique=True, verbose_name='收據編號')),
                ('receipt_to', models.CharField(blank=True, max_length=255, verbose_name='收據抬頭')),
                ('taxid', models.CharField(blank=True, max_length=50, null=True, verbose_name='統一編號')),
                ('date', models.DateField(verbose_name='收據日期')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL, verbose_name='建立人')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='business.order', verbose_name='關聯訂單')),
            ],
            options={
                'verbose_name': '收據',
                'verbose_name_plural': '收據',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, verbose_name='產品名稱')),
                ('product_code', models.CharField(blank=True, max_length=255, verbose_name='產品代碼')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='單價')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='business.orderproduct', verbose_name='關聯訂單產品')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.receipt', verbose_name='收據')),
            ],
            options={
                'verbose_name': '收據明細',
                'verbose_name_plural': '收據明細',
                'ordering': ['id'],
            },
        ),
    ]
