# Generated by Django 4.2.24 on 2025-11-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_receipt_receiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('ORDER', '訂單'), ('MANUAL', '手動')], default='ORDER', help_text='訂單收據或手動建立', max_length=20, verbose_name='收據類型'),
        ),
    ]
