# Generated by Django 4.2.24 on 2025-11-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_receipt_receipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('NORMAL', '正常'), ('FAILED', '失敗'), ('CANCELED', '已取消'), ('RETURNED', '已退貨'), ('DAMAGED', '損壞')], default='NORMAL', max_length=20, verbose_name='訂單產品狀態'),
        ),
    ]
