# Generated by Django 4.2.24 on 2025-11-21 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercoupons',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.order'),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='business.orderproduct', verbose_name='關聯訂單產品'),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='pin1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='pin2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='product_expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='產品過期時間'),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='puk1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='puk2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='qrcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='sale_plan_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='sale_plan_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='sn_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='sn_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='trans_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordercoupons',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordercoupons',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
