# Generated by Django 4.2.24 on 2025-12-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_ordercoupons_created_at_ordercoupons_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='item',
            field=models.CharField(choices=[('SALES', '銷售收入'), ('SERVICE_FEE', '服務費收入'), ('INVESTMENT', '投資收入'), ('RENT', '租金收入'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='收入項目'),
        ),
    ]
