# Generated by Django 4.2.24 on 2025-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_order_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, choices=[('ERP', 'ERP系統'), ('SHOPEE', '蝦皮商城'), ('COUPANG', '酷澎'), ('WEBSITE', '官網'), ('LINE', 'LINE'), ('HANDOVER', '面交'), ('PEER', '同業'), ('OTHER', '其他')], max_length=50, null=True, verbose_name='訂單來源'),
        ),
    ]
