# Generated by Django 4.2.24 on 2025-10-23 17:03

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, verbose_name='分類描述')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='產品名稱')),
                ('description', models.TextField(blank=True, verbose_name='產品描述')),
                ('status', models.CharField(choices=[('ACTIVE', '上架'), ('INACTIVE', '下架'), ('ARCHIVED', '封存')], default='INACTIVE', max_length=20, verbose_name='產品狀態')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='產品分類')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供應商名稱')),
                ('description', models.TextField(blank=True, verbose_name='供應商描述')),
                ('supplier_code', models.CharField(max_length=50, unique=True, verbose_name='供應商代碼')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='產品變體名稱')),
                ('description', models.TextField(blank=True, verbose_name='變體描述')),
                ('status', models.CharField(choices=[('ACTIVE', '上架'), ('INACTIVE', '下架'), ('ARCHIVED', '封存')], default='ACTIVE', max_length=20, verbose_name='產品變體狀態')),
                ('product_type', models.CharField(choices=[('esim', 'eSIM'), ('esimimg', '圖庫eSIM'), ('rechargeable', '充值卡'), ('physical', '成品卡')], default='esim', max_length=20, verbose_name='產品類型')),
                ('product_code', models.CharField(blank=True, max_length=255)),
                ('days', models.CharField(max_length=100, verbose_name='方案天數')),
                ('data_amount', models.CharField(max_length=50, verbose_name='方案規格')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='方案價格')),
                ('price_sales', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='方案特價')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='產品')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variants',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='庫存名稱')),
                ('description', models.TextField(blank=True, verbose_name='庫存描述')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='二維碼圖片')),
                ('initial_quantity', models.IntegerField(default=0, verbose_name='初始庫存數量')),
                ('quantity', models.IntegerField(default=0, verbose_name='庫存數量')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='過期時間')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('exchange_time', models.DateTimeField(blank=True, null=True, verbose_name='兌換時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.variant', verbose_name='產品')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'ordering': ['-created_at'],
            },
        ),
    ]
