# Generated by Django 4.2.24 on 2025-10-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='price_agent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='代理商方案價格'),
        ),
        migrations.AddField(
            model_name='variant',
            name='price_sales_agent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='代理商方案特價'),
        ),
    ]
