# Generated by Django 4.2.24 on 2025-11-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_order_shipping_fee'),
        ('products', '0002_variant_price_agent_variant_price_sales_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_stocks', to='business.order', verbose_name='關聯訂單'),
        ),
    ]
