# Generated by Django 4.2.24 on 2025-11-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stock_related_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='related_order',
        ),
    ]
