# Generated by Django 4.2.24 on 2025-11-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_stock_related_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=255, verbose_name='SKU'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'is_used', 'quantity'], name='products_st_product_624885_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['code'], name='products_st_code_efca0a_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['expire_date'], name='products_st_expire__d10af7_idx'),
        ),
    ]
