# Generated by Django 4.2.24 on 2025-11-21 07:59

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variant_sku_stock_products_st_product_624885_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='qr_img',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.stock_qr_image_path, verbose_name='二維碼圖片'),
        ),
    ]
