# Generated by Django 4.2.24 on 2025-12-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_stock_qr_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='price_distr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='經銷商方案價格'),
        ),
        migrations.AddField(
            model_name='variant',
            name='price_peer',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='同業商方案價格'),
        ),
        migrations.AddField(
            model_name='variant',
            name='price_sales_distr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='經銷商方案特價'),
        ),
        migrations.AddField(
            model_name='variant',
            name='price_sales_peer',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='同業商方案特價'),
        ),
    ]
