# Generated by Django 4.2.24 on 2025-12-01 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_variant_price_distr_variant_price_peer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='price_distr',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='price_sales_distr',
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='一般價'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_agent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='代理商拿貨價'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_peer',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='同業價'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_sales',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='一般特價'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_sales_agent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='代理商拿貨特價'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_sales_peer',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='同業特價'),
        ),
        migrations.CreateModel(
            name='AgentDistributorPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_distr', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='經銷價格')),
                ('price_sales_distr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='經銷特價')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_pricings', to='products.variant')),
            ],
            options={
                'verbose_name_plural': '代理商自訂經銷價格',
                'unique_together': {('variant', 'agent')},
            },
        ),
    ]
