# Generated by Django 4.2.24 on 2025-12-06 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_variant_price_distr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.supplier', verbose_name='供應商'),
        ),
    ]
